version: '3'
services:
  banca:
    build: .
    ports:
      - "4200:4200"
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub

  selenium-hub:
    image: selenium/hub:4.1.0
    ports:
      - "4444:4444"
      
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
